development:
  adapter: postgresql
  encoding: unicode
  database: pos_d
  host: localhost
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: pos_t
  host: localhost
  pool: 5

production:
  adapter: postgresql
  host: /tmp
  encoding: unicode
  database: pos_p
  pool: 5
